# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# License found in the LICENSE file in the root directory
# of this source tree.
version: '3.3'

services:
  proxy:
    container_name: whatsapp_proxy
    build: ../
    restart: unless-stopped
    ports:
      - "22:22"     # SSH
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
      - "5222:5222" # JABBER
      - "8199:8199" # HAPROXY statistics page
      - "8080:8080" # HTTP with accept-proxy processing
      - "8443:8443" # HTTPS with accept-proxy processing
      - "8222:8222" # JABBER with accept-proxy processing
    healthcheck:
      test: /usr/local/bin/healthcheck.sh
      interval: 10s
      start_period: 5s
    environment:
      - PUBLIC_IP=10.0.0.1
    # sysctls:
      # - net.core.somaxconn=1024
      # - net.ipv4.tcp_mem="786432 1048576 1572864"
      # - net.ipv4.tcp_rmem="4096 1048576 10485760"
      # - net.ipv4.tcp_wmem="4096 1048576 10485760"
      # - net.core.rmem_max=10485760
      # - net.core.wmem_max=10485760
      # - net.ipv4.tcp_timestamps=0
      # - net.ipv4.tcp_max_orphans=262144
      # - net.ipv4.tcp_max_sync_backlog=65536
      # - net.core.netdev_max_backlog=16384
      # - fs.file-max=10485760
      # - net.ipv4.tcp_retries2=8
