# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# License found in the LICENSE file in the root directory
# of this source tree.

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          # ct needs history to compare
          fetch-depth: 0
      - name: Build the Docker image
        run: docker build ./proxy/ --tag whatsapp_proxy:$(date +%s)

      - name: Lint the Helm chart (whatsapp-proxy-chart)
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint
          config: ct.yaml
