# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# License found in the LICENSE file in the root directory
# of this source tree.
name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
        # The :11 strips the first 11 characters from the environment variable GITHUB_REF which contains refs/tags/v1.2.3 so it yields 1.2.3
      - name: Set release version (i.e. tag)
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/v}

      - name: Print the release version (i.e. tag)
        run: echo "TAG = ${{ steps.vars.outputs.tag }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./proxy
          push: true
          tags: seanlawlor/whatsapp_proxy:${{ steps.vars.outputs.tag }}
